### ISSUE TITLE
Error in lagosne_load()

### ISSUE THREAD

**Issue by mfa54** [cont-limno/LAGOSNE#100]
After successfully installing the LAGOSNE package in R, and after successfully downloading all the LAGOSNE data using lagosne_get(), I am facing an error when loading the data using the following command:
dt <- lagosne_load().
The error is as follows:
> dt <- lagosne_load()
Loading LAGOSNE version: 1.087.1
Error in stop_if_not_exists(rds_path) : 
  Dataset not found at: C:\Users\M.A\AppData\Local\LAGOSNE\LAGOSNE/data_1.087.1.rds
 Try running the `lagosne_get` command.

**Comment by jsta** [comment]
Hi @mfa54. The error is informing you that you have not yet downloaded the data with the `lagosne_get` command. I recommend running: `lagosne_get(dest_folder = LAGOSNE:::lagos_path())`

**Comment by mfa54** [comment]
Hello @jsta. Than you for your reply.
Just to make it more clear for everyone reading this issue. I have previously tried lagosne_get() only, and obtained the aforementioned error. However after using the command: lagosne_get(dest_folder = LAGOSNE:::lagos_path()), suggested by @jsta, the error no longer occurred, and I am now able to access the data successfully, thanks to @jsta.
