### ISSUE TITLE
Error with lagosne_get (cannot open URL)

### ISSUE THREAD

**Issue by KateriSalk** [cont-limno/LAGOSNE#106]
I'm getting the following error when I run the function `lagosne_get`: 

trying URL 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.100.4&entityid=ce274065dfb5b453c5696f715fe4e269'
cannot open URL 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.100.4&entityid=ce274065dfb5b453c5696f715fe4e269': HTTP status was '500 Internal Server Error'Error in download.file(url, destfile) : 
  cannot open URL 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.100.4&entityid=ce274065dfb5b453c5696f715fe4e269'

This happens regardless of whether I specify the destination folder, overwrite statement, or version. The URL given in the error message is identical regardless of whether I request version 1.01, 1.054.1, or 1.087.1. When I post the url in a browser, it successfully downloads a csv file. I'm running R version 3.6.1, R Studio version 1.2.1335, and Mac OS Mojave.

Any tips or insights?

**Comment by jsta** [comment]
I'm in the process of upgrading to `1.087.3`. For now, I recommend installing the package version from several days ago and pulling `1.087.1`: 

```
devtools::install_github("cont-limno/LAGOSNE", ref = "v1.087.1")
lagosne_get("1.087.1")
```

**Comment by KateriSalk** [comment]
Looks like I chose the wrong day to start exploring LAGOSNE! Glad to know my issue wasn't just user error. The code you provided runs without error. Any estimate on when 1.087.3 will be ready?

I'll be using this package in my Hydrologic Data Analysis course this upcoming semester. Can't wait! Thanks for your help.

**Comment by jsta** [comment]
Should work now. The latest version is on CRAN. Good luck with your course!
