### ISSUE TITLE
Temperature?

### ISSUE THREAD

**Issue by jhollist** [cont-limno/LAGOSNE#62]
Got a chance to dig into the data a bit today and didn't notice water temperature anywhere.  

Is it included in the LAGOSNE dataset?  If not, does it exist?

**Comment by jsta** [comment]
No temperature data yet. We have plans to include it in future data products. Parsing profile data is not as straightforward as grab data.

**Comment by jhollist** [comment]
Thanks, @jsta.  We wait with baited breath!

Any way we can help with it, let me know.

**Comment by jhollist** [comment]
@jsta,  just circling back on this to see if any updates on when temperature data for the LAGOSNE sites is expected?  Thanks!

**Comment by limnoliver** [comment]
@jhollist just wanted to let you know we're doing some temperature assimilation at the USGS -- both building on the [Winslow et al.](https://www.nature.com/articles/sdata201753) work in the Midwest (which includes getting data from unpublished sources) and a national-extent effort which is mostly compiling publicly available data.

**Comment by jhollist** [comment]
Cool!  What's the time frame on that being available?  Is it a near-term thing (month or so) or longer-term (6 months out).

**Comment by limnoliver** [comment]
Longer term. Also, as an aside, did I hear you'll be in Madison this summer? If so, we should grab a beverage and chat about the above. Would like to meet you IRL!

**Comment by jsta** [comment]
Closing this as we are planning to include temperature in a different forthcoming data product (LAGOSUS).
