### ISSUE TITLE
Sample Depth?

### ISSUE THREAD

**Issue by jhollist** [cont-limno/LAGOSNE#71]
Still loving the package!  

Where is the sample depth for the epi_nutr data?  I've been digging around in the package documentation and the only depths I can find are for secchi or the lake, nothing for each of the samples.

**Comment by jhollist** [comment]
Thanks @jsta   Is that from: https://academic.oup.com/gigascience/article/6/12/1/4555226?

I was digging through https://gigascience.biomedcentral.com/articles/10.1186/s13742-015-0067-4 , in particular Figure 6, which suggests that it was available.  

Understand that it is not available at this time!  Would love to discuss at a later date the challenges with the depth info as it pertains to this and temperature!  Perhaps in person and over a beer.

Will close this for now.

**Comment by jsta** [comment]
Yes, but see @soranno comments on #72
