### ISSUE TITLE
back to sample depth issue

### ISSUE THREAD

**Issue by soranno** [cont-limno/LAGOSNE#72]
joe and jeff -- just to be clear -- some data value coming in have an actual sample depth associated with them (ie, 1m or surface) and other programs just said they sampled the 'epilimnion'. we combined grab samples and integrated tube samples (of the epi). in our master database, we have some additional samples from the metalimnion and hypo from some lakes but we did not export them. in our next version of LAGOS-US, we may think about exporting all values from all depths, but we wanted an easy dataset that we interpreted  to be epilimnetic for easy statistical analysis. if you feel like you have an application to make use of data from other depths, please let us know and we can probably get you a data export. i am new to communicating over github - i assume this has reach both of you?

**Comment by jsta** [comment]
I assume this is to be revisited in LAGOS-US
